import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head><script defer async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9138119079477333"
     crossorigin="anonymous"></script></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
<div className="flex p-4">
  🎯 Word Guess Game – Test Your Vocabulary Skills!

Put your word skills to the test with Word Guess Game, a fun and addictive game where every letter counts! Whether you're a casual player or a word puzzle pro, this game challenges your brain and sharpens your vocabulary one word at a time.

🧠 How to Play:

Guess the hidden word by entering letters or words.

Get instant feedback: correct letters in the right place, wrong place, or not in the word at all.

Use logic, memory, and deduction to crack the word within limited attempts!

🌟 Features:

Clean, minimal design for smooth gameplay

Great for all ages — perfect for learning and fun

🔤 Play solo or challenge friends — how many words can you guess right?
  </div>
      </body>
    </html>
  );
}
